### ISSUE TITLE
Missing access modifier?

### ISSUE THREAD

**Issue by ergonic** [pjanku/OSMParser#7]
The structure [Way](https://github.com/pjanku/OSMParser/blob/8e7864a2efac80388be550907ca1db3c9701ba5a/include/osmparser.h#L43)
don't contain any access modifier (which I believe is fine since the default behavior is that each member in the structure is public). However, in UE project, the isClosed is not visible. Only after I add public: before it, it is accesible.

**Comment by pjanku** [comment]
From my point of view, the "public" modificator is not necessary because I think that default members' visibility in a struct is "public". Your description leads me to the idea, that you had a previous version of the library (without isClosed) and the project hasn't realised the change.
